export const START_SETUP_USER = "START_SETUP_USER";
export const SUCCESS_SETUP_USER = "SUCCESS_SETUP_USER";
export const ERROR_SETUP_USER = "ERROR_SETUP_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const HIDE_ALERT = "HIDE_ALERT";
export const TOGGLE_MOBILE_NAV = "TOGGLE_MOBILE_NAV";

export const START_UPDATE_USER = "START_UPDATE_USER";
export const SUCCESS_UPDATE_USER = "SUCCESS_UPDATE_USER";
export const ERROR_UPDATE_USER = "ERROR_UPDATE_USER";
