/**
 * User and Auth actions
 */
export const START_SETUP_USER = 'START_SETUP_USER';
export const SUCCESS_SETUP_USER = 'SUCCESS_SETUP_USER';
export const ERROR_SETUP_USER = 'ERROR_SETUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const START_UPDATE_USER = 'START_UPDATE_USER';
export const SUCCESS_UPDATE_USER = 'SUCCESS_UPDATE_USER';
export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';

/**
 * Ticket Actions
 */
export const START_CREATE_TICKET = 'START_CREATE_TICKET';
export const SUCCESS_CREATE_TICKET = 'SUCCESS_CREATE_TICKET';
export const ERROR_CREATE_TICKET = 'ERROR_CREATE_TICKET';

export const START_DELETE_TICKET = 'START_DELETE_TICKET';
export const SUCCESS_DELETE_TICKET = 'SUCCESS_DELETE_TICKET';
export const ERROR_DELETE_TICKET = 'ERROR_DELETE_TICKET';

export const START_UPDATE_TICKET = 'START_UPDATE_TICKET';
export const SUCCESS_UPDATE_TICKET = 'SUCCESS_UPDATE_TICKET';
export const ERROR_UPDATE_TICKET = 'ERROR_UPDATE_TICKET';

export const START_GET_TICKETS = 'START_GET_TICKETS';
export const SUCCESS_GET_TICKETS = 'SUCCESS_GET_TICKETS';
export const ERROR_GET_TICKETS = 'ERROR_GET_TICKETS';

export const START_EDIT_TICKET = 'START_EDIT_TICKET';
export const SUCCESS_EDIT_TICKET = 'SUCCESS_EDIT_TICKET';
export const ERROR_EDIT_TICKET = 'ERROR_EDIT_TICKET';

/**
 * MISC Actions
 */
export const HIDE_ALERT = 'HIDE_ALERT';
export const TOGGLE_MOBILE_NAV = 'TOGGLE_MOBILE_NAV';
